### ISSUE TITLE
重启路由器后，无法连接！

### ISSUE THREAD

**Issue by supra007** [qoli/Merlin.PHP#10]
原来用着好的，在安装了“梅林首页增加部分系统信息”插件后，重启路由器后就打不开192.168.2.1:81网页了，重新安装软件包还是不行！

**Comment by qoli** [comment]
重新走一次安裝流程呢？
雙硬盤路由器會有一個偶發 Bug 就是兩個硬盤掛載位置反轉了。

我建議你這樣做，1. 再重啓一次，測試；2. 不行就再從 Download Master 的步驟裝一次。

**Comment by supra007** [comment]
谢谢美女大师，全部重新安装解决了问题，看来路由器重启的话要重新安装？

**Comment by qoli** [comment]
不是這樣的。
是你的 ipkg 環境沒有被保存。
檢查連接的 USB 設備。
不過，我也遇到過這種情況。
