### ISSUE TITLE
安装一切正常，可登录81端口显示192.168.1.1 拒绝了我们的连接请求。

### ISSUE THREAD

**Issue by kingofotaku** [qoli/Merlin.PHP#11]
rt 这是我用chrome的提示 错误信息是ERR_CONNECTION_REFUSED
安装过程并无报错，就是打不开（换过其他端口结果一样没用）

**Comment by qoli** [comment]
參考這個試試：
https://www.quora.com/How-do-I-fix-ERR_CONNECTION_REFUSED-on-Chrome

**Comment by qoli** [comment]
這個是中文答案：
- 將防毒軟體與防火牆設定為允許 Google Chrome
- 調整 Proxy 設定

**Comment by kingofotaku** [comment]
感谢回复。已尝试上面提到的设置并试着更换浏览器，结果依然无效。还有就是之前有尝试重新格式化u盘，重新安装，结果安装完后可以打开，但第二天重新启动路由器之后就又不行了

**Comment by qoli** [comment]
估計你的外接設備或者 opkg 環境在重啓後，被初始化了。

**Comment by kingofotaku** [comment]
这要如何解决

**Comment by qoli** [comment]
http://www.snbforums.com/threads/entware-after-reboot.10933/

Google: Merlin reboot opkg.

**Comment by ghhp** [comment]
作者你好。這個軟件對我特別有用，但我現在也是這種情況，只要重啓一次路由就再也打不開了。固件刷好之後我應該沒改動過什麽設置。可以簡單告訴我們一下怎樣解決嗎？

**Comment by qoli** [comment]
我建議你們檢查這些：
- jffs 是否有打開；
- 移動磁碟是否是 Ext4 格式（最好，理論上支持 FAT32 \ NTFS \ Mac 日誌式等）；
- 用「mount」命令檢查外接磁碟是否可被讀寫。
- Google 查找「entware gone after reboot」

我無法得知這是為何原因，entware 會消失了。

**Comment by ghhp** [comment]
格成ext4之後解決了。多謝指點。
