### ISSUE TITLE
希望推出卸载脚本

### ISSUE THREAD

**Issue by prolene** [qoli/Merlin.PHP#13]
谢谢：）

**Comment by qoli** [comment]
如果 Download Master 所使用的磁碟沒裝什麼東西的話。
可以把 Download Master 格式化即可。

有的話。
移除 /opt/share/www 后，對 Download Master 點擊「uninstall」。

**Comment by prolene** [comment]
回复的好快
因为改版固件安装时要求插u盘设置jffs分区，所以我不知道shadowsocks的相关文件和设置是不是放在这个分区内

另外merlin-php的包里把.DS_Store文件也都打包进去了

**Comment by prolene** [comment]
补充：还要卸载lighttpd，ipkg remove lighttpd

**Comment by qoli** [comment]
你對 download master uninstall 就是把 ipkg 環境卸載了。還 remove 什麼程序呢？

**Comment by prolene** [comment]
但是uninstall以后发现lighttpd还在运行，于是手动ipkg remove了一下

**Comment by qoli** [comment]
你重啟就沒了。
linux 是可以刪除正在運行的文件。

2016年8月15日 +0800 AM10:12 prolene notifications@github.com，写道：
