### ISSUE TITLE
最新版的SS，插件的google状态一直红

### ISSUE THREAD

**Issue by jinfeng1985** [qoli/Merlin.PHP#20]
但后台看了下SS是working状态。

**Comment by qoli** [comment]
我會安排時間查詢一下了。

Google 檢查是利用 DNS2SOCKS 功能的，如果 SS 設定不是 DNS2SOCKS 的話，就會一直紅。可能在最新版一些端口改變了。

**Comment by qoli** [comment]
已经在最新版测试，功能可用。
