### ISSUE TITLE
二级路由下网络状态识别不正确

### ISSUE THREAD

**Issue by hackkyo** [qoli/Merlin.PHP#21]
![qq 20161016223033](https://cloud.githubusercontent.com/assets/22870084/19418142/c0016472-93f0-11e6-90b0-cb1183f27992.png)
![qq 20161016223100](https://cloud.githubusercontent.com/assets/22870084/19418143/c011f3c8-93f0-11e6-8ff8-eea892995425.png)
如上图所示

**Comment by qoli** [comment]
好的，我遲些推出一個抓取 Debug 的工具，會幫助處理這個問題的。
