### ISSUE TITLE
更新了一下Download Master後工具打不開了

### ISSUE THREAD

**Issue by ghhp** [qoli/Merlin.PHP#22]
如題。卸載DM、格式化u盤然後重裝DM和工具後還是不行。懷疑是最新版DM(102)造成的。求救。
固件7.5，ss3.6.0

**Comment by qoli** [comment]
我調查一下。

**Comment by ghhp** [comment]
抱歉，好像是我自己的問題。
把u盤格成ext2後再重裝，又好了。
最近聯通國際出口問題嚴重，實在離不開本工具。

**Comment by ghhp** [comment]
切換綫路/模式和停止ss(STOP)工作不正常

把所有都重裝了一遍：固件7.2、ss3.6.0、下載大師3.1.0.102、u盤是ext4
停止ss(STOP)點擊後馬上就沒反應了。實際ss並沒停止。
切換綫路或模式，比如在一個原版綫路和一個ssr綫路閒切換後，ss就會不通。此時在後臺可看到ss-redir和ss-local都是"未運行"。
是否和ss3.5.9合併了腳本有關？

另請問，能否提供舊版下載？(想試試0.5.10)
多謝。

**Comment by qoli** [comment]
清理瀏覽器緩存就正常了

**Comment by ghhp** [comment]
清了一下，還是一樣。STOP完全無效。切換偶爾會正常但基本無效(有時會導致SS死掉)。
圖片是同個綫路從gfwlist切到大陸白時。實際從ip111.cn看還是gfwlist狀態。右邊有個滾動條，但沒法向上滾，會被拖下來。而且以前的工具有個類似"chn mode successfully enabled"的英文提示，這個日誌裏沒有任何關於"大陸白"的字樣。
感謝這麽晚回復。拜托有空時調查一下。

![snap4](https://user-images.githubusercontent.com/15943694/29724747-463ae494-89fc-11e7-8e27-ebff3fbd5493.jpg)

**Comment by qoli** [comment]
好的，我測試一下。GFW 和 遊戲模式，還有 STOP。
我都沒認真測試⋯

右邊的進度條是無法推動的，會自動往下啦。這個調整要寫判斷代碼，我偷懶了喔！

另外，PHP 版的項目以及暫緩了，會推出基於 C 重寫的版本哦。可以在插件中心安裝的新版本了。

https://github.com/qoli/Merlin.C

**Comment by ghhp** [comment]
喔喔，期待新版 :--)

**Comment by ghhp** [comment]
報告。更新0.6.3後STOP復活了。但切換的問題依舊。

**Comment by qoli** [comment]
切換應該可以了，就是管理後台的顯示不同步。我正在尋找 3.6.0 的 SS 後台是不是改變了一些信息結構。

**Comment by ghhp** [comment]
嗯。。。我這邊試了多次還和上次一樣，比如同個綫路從gfwlist切到大陸白時，日誌裏&實測都還是gfwlist狀態。
![snap2](https://user-images.githubusercontent.com/15943694/30101770-209707e0-9320-11e7-8933-38397f562973.jpg)

**Comment by qoli** [comment]
好的。我理解了。

SS 3.6.0 模式讀取方案調整了。我暫時還沒找到對應的關鍵字。

你調整模式先暫時到管理後台去吧。把這裡當成是重啟 SS 的地方先。估計下一個版本就解決這個問題了

**Comment by qoli** [comment]
0.6.4 解決這個問題了。
這個問題來自於我的一個語法錯誤。

因為有段時間沒寫 PHP 了，這個語法錯誤我一直沒有發現。

**Comment by ghhp** [comment]
0.6.4
模式的確沒問題了。
但我這裡從一條綫路切換到另一條ssr綫路時(就是説只要切換後是ssr時)，一定會導致插件進程消失。同一綫路内切換模式、切換到ss等都正常。
