### ISSUE TITLE
7.6安装完无法打开

### ISSUE THREAD

**Issue by jackiejtr** [qoli/Merlin.PHP#23]
打不开192.168.1.1:81

**Comment by qoli** [comment]
安裝過程中發生了錯誤，安裝腳本檢測不到的。你需要提交安裝流程的日誌輸出已確認錯誤位置。

**Comment by jackiejtr** [comment]
是這種日誌么
ASUSWRT-Merlin RT-AC56U 380.67-X7.6 Fri Aug 18 01:46:21 UTC 2017
jackiejtr@RT-AC56R-6DE8:/tmp/home/root# wget --no-check-certificate https://gith
ub.com/qoli/Merlin.PHP/raw/master/bin/install/install.sh -O install.sh
--2017-10-07 01:51:26--  https://github.com/qoli/Merlin.PHP/raw/master/bin/install/install.sh
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/qoli/Merlin.PHP/master/bin/install/install.sh [following]
--2017-10-07 01:51:28--  https://raw.githubusercontent.com/qoli/Merlin.PHP/master/bin/install/install.sh
Resolving raw.githubusercontent.com... 151.101.76.133
Connecting to raw.githubusercontent.com|151.101.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1416 (1.4K) [text/plain]
Saving to: 'install.sh'

install.sh          100%[=====================>]   1.38K  --.-KB/s   in 0s

2017-10-07 01:51:28 (33.1 MB/s) - 'install.sh' saved [1416/1416]

jackiejtr@RT-AC56R-6DE8:/tmp/home/root# chmod +x install.sh
jackiejtr@RT-AC56R-6DE8:/tmp/home/root# ./install.sh

■ script - 2017-09-06 19:12:16

■ INSTALL Merlin.PHP

■ 「STEP 1」optware

--2017-10-07 01:51:48--  http://t.cn/RpPFqUm
Resolving t.cn... 180.149.135.224
Connecting to t.cn|180.149.135.224|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.llqoli.com/ipks/optware-ngu-setup.sh [following]
--2017-10-07 01:51:48--  http://www.llqoli.com/ipks/optware-ngu-setup.sh
Resolving www.llqoli.com... 2400:cb00:2048:1::681c:94e, 104.28.8.78, 104.28.9.78
Connecting to www.llqoli.com|2400:cb00:2048:1::681c:94e|:80... failed: Network is unreachable.
Connecting to www.llqoli.com|104.28.8.78|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

 Info:  This script was created by ryzhov_al and modified by TeHashX.
 Info:  Thanks @alllexx88 for New Generation Optware
 Info:  and @Rmerlin for his awesome firmwares
 Info:  This script will guide you through the Optware-NG installation.
 Info:  Script modifies only "optware-ng" folder on the chosen drive,
 Info:  no other data will be touched. Existing installation will be
 Info:  replaced with this one. Also some start scripts will be installed,
 Info:  the old ones will be saved on partition where Optware-NG is installed
 Info:  like /tmp/mnt/sda1/jffs_scripts_backup.tgz

 Info:  Looking for available partitions...
 *** Error:  No ext2|ext3|ext4 partitions available. Exiting...

■ INSTALL Merlin.PHP

■ 「STEP 2」software
./install.sh: line 17: ipkg: not found
./install.sh: line 18: ipkg: not found
./install.sh: line 19: ipkg: not found
sed: /opt/etc/lighttpd/lighttpd.conf: No such file or directory
./install.sh: line 21: /opt/etc/init.d/S80lighttpd: not found
/usr/sbin/app_set_enabled.sh: line 33: ipkg: not found
The "lighttpd" is not installed yet!

■ 「STEP 3」CODE

--2017-10-07 01:51:51--  https://github.com/qoli/Merlin.PHP/raw/master/bin/zip/merlin-php.tar.gz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/qoli/Merlin.PHP/master/bin/zip/merlin-php.tar.gz [following]
--2017-10-07 01:51:52--  https://raw.githubusercontent.com/qoli/Merlin.PHP/master/bin/zip/merlin-php.tar.gz
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4036579 (3.8M) [application/octet-stream]
Saving to: 'merlin-php.tar.gz'

merlin-php.tar.gz   100%[=====================>]   3.85M  3.00MB/s   in 1.3s

2017-10-07 01:51:54 (3.00 MB/s) - 'merlin-php.tar.gz' saved [4036579/4036579]

drwxrwxrwx    2 jackiejt root            60 Oct  7 01:51 .
drwxrwxrwx   13 jackiejt root           880 Oct  7 01:51 ..
-rw-rw-rw-    1 jackiejt root       4036579 Oct  7 01:51 merlin-php.tar.gz
▣ All is readly, Do you want to install [y/n] ? y
■ extract...
Merlin.PHP/
Merlin.PHP/api.php
Merlin.PHP/app.php
Merlin.PHP/article/
Merlin.PHP/assets/
Merlin.PHP/bin/
Merlin.PHP/config/
Merlin.PHP/exec.php
Merlin.PHP/favicon.ico
Merlin.PHP/fonts/
Merlin.PHP/images/
Merlin.PHP/index.php
Merlin.PHP/library/
Merlin.PHP/pages/
Merlin.PHP/README.md
Merlin.PHP/update.php
Merlin.PHP/pages/.DS_Store
Merlin.PHP/pages/_end.php
Merlin.PHP/pages/_head.php
Merlin.PHP/pages/_setting-config.php
Merlin.PHP/pages/_ui.php
Merlin.PHP/pages/article.php
Merlin.PHP/pages/b.php
Merlin.PHP/pages/dashboard.php
Merlin.PHP/pages/Footer.php
Merlin.PHP/pages/home.php
Merlin.PHP/pages/LeftMenu.php
Merlin.PHP/pages/plugin.php
Merlin.PHP/pages/remote-edit.php
Merlin.PHP/pages/remote.php
Merlin.PHP/pages/setting.php
Merlin.PHP/pages/shadowvpn.php
Merlin.PHP/library/.DS_Store
Merlin.PHP/library/AppFunction.php
Merlin.PHP/library/MainFunction.php
Merlin.PHP/library/phpseclib/
Merlin.PHP/library/Requests/
Merlin.PHP/library/Requests.php
Merlin.PHP/library/Requests/.DS_Store
Merlin.PHP/library/Requests/Auth/
Merlin.PHP/library/Requests/Auth.php
Merlin.PHP/library/Requests/Cookie/
Merlin.PHP/library/Requests/Cookie.php
Merlin.PHP/library/Requests/Exception/
Merlin.PHP/library/Requests/Exception.php
Merlin.PHP/library/Requests/Hooker.php
Merlin.PHP/library/Requests/Hooks.php
Merlin.PHP/library/Requests/IDNAEncoder.php
Merlin.PHP/library/Requests/IPv6.php
Merlin.PHP/library/Requests/IRI.php
Merlin.PHP/library/Requests/Proxy/
Merlin.PHP/library/Requests/Proxy.php
Merlin.PHP/library/Requests/Response/
Merlin.PHP/library/Requests/Response.php
Merlin.PHP/library/Requests/Session.php
Merlin.PHP/library/Requests/SSL.php
Merlin.PHP/library/Requests/Transport/
Merlin.PHP/library/Requests/Transport.php
Merlin.PHP/library/Requests/Utility/
Merlin.PHP/library/Requests/Utility/CaseInsensitiveDictionary.php
Merlin.PHP/library/Requests/Utility/FilteredIterator.php
Merlin.PHP/library/Requests/Transport/cacert.pem
Merlin.PHP/library/Requests/Transport/cURL.php
Merlin.PHP/library/Requests/Transport/fsockopen.php
Merlin.PHP/library/Requests/Response/Headers.php
Merlin.PHP/library/Requests/Proxy/HTTP.php
Merlin.PHP/library/Requests/Exception/HTTP/
Merlin.PHP/library/Requests/Exception/HTTP.php
Merlin.PHP/library/Requests/Exception/HTTP/400.php
Merlin.PHP/library/Requests/Exception/HTTP/401.php
Merlin.PHP/library/Requests/Exception/HTTP/402.php
Merlin.PHP/library/Requests/Exception/HTTP/403.php
Merlin.PHP/library/Requests/Exception/HTTP/404.php
Merlin.PHP/library/Requests/Exception/HTTP/405.php
Merlin.PHP/library/Requests/Exception/HTTP/406.php
Merlin.PHP/library/Requests/Exception/HTTP/407.php
Merlin.PHP/library/Requests/Exception/HTTP/408.php
Merlin.PHP/library/Requests/Exception/HTTP/409.php
Merlin.PHP/library/Requests/Exception/HTTP/410.php
Merlin.PHP/library/Requests/Exception/HTTP/411.php
Merlin.PHP/library/Requests/Exception/HTTP/412.php
Merlin.PHP/library/Requests/Exception/HTTP/413.php
Merlin.PHP/library/Requests/Exception/HTTP/414.php
Merlin.PHP/library/Requests/Exception/HTTP/415.php
Merlin.PHP/library/Requests/Exception/HTTP/416.php
Merlin.PHP/library/Requests/Exception/HTTP/417.php
Merlin.PHP/library/Requests/Exception/HTTP/418.php
Merlin.PHP/library/Requests/Exception/HTTP/428.php
Merlin.PHP/library/Requests/Exception/HTTP/429.php
Merlin.PHP/library/Requests/Exception/HTTP/431.php
Merlin.PHP/library/Requests/Exception/HTTP/500.php
Merlin.PHP/library/Requests/Exception/HTTP/501.php
Merlin.PHP/library/Requests/Exception/HTTP/502.php
Merlin.PHP/library/Requests/Exception/HTTP/503.php
Merlin.PHP/library/Requests/Exception/HTTP/504.php
Merlin.PHP/library/Requests/Exception/HTTP/505.php
Merlin.PHP/library/Requests/Exception/HTTP/511.php
Merlin.PHP/library/Requests/Exception/HTTP/Unknown.php
Merlin.PHP/library/Requests/Cookie/Jar.php
Merlin.PHP/library/Requests/Auth/Basic.php
Merlin.PHP/library/phpseclib/.DS_Store
Merlin.PHP/library/phpseclib/Crypt/
Merlin.PHP/library/phpseclib/File/
Merlin.PHP/library/phpseclib/Math/
Merlin.PHP/library/phpseclib/Net/
Merlin.PHP/library/phpseclib/openssl.cnf
Merlin.PHP/library/phpseclib/System/
Merlin.PHP/library/phpseclib/System/SSH/
Merlin.PHP/library/phpseclib/System/SSH_Agent.php
Merlin.PHP/library/phpseclib/System/SSH/Agent.php
Merlin.PHP/library/phpseclib/Net/.DS_Store
Merlin.PHP/library/phpseclib/Net/SCP.php
Merlin.PHP/library/phpseclib/Net/SFTP/
Merlin.PHP/library/phpseclib/Net/SFTP.php
Merlin.PHP/library/phpseclib/Net/SSH1.php
Merlin.PHP/library/phpseclib/Net/SSH2.php
Merlin.PHP/library/phpseclib/Net/SFTP/Stream.php
Merlin.PHP/library/phpseclib/Math/BigInteger.php
Merlin.PHP/library/phpseclib/File/ANSI.php
Merlin.PHP/library/phpseclib/File/ASN1.php
Merlin.PHP/library/phpseclib/File/X509.php
Merlin.PHP/library/phpseclib/Crypt/AES.php
Merlin.PHP/library/phpseclib/Crypt/Base.php
Merlin.PHP/library/phpseclib/Crypt/Blowfish.php
Merlin.PHP/library/phpseclib/Crypt/DES.php
Merlin.PHP/library/phpseclib/Crypt/Hash.php
Merlin.PHP/library/phpseclib/Crypt/Random.php
Merlin.PHP/library/phpseclib/Crypt/RC2.php
Merlin.PHP/library/phpseclib/Crypt/RC4.php
Merlin.PHP/library/phpseclib/Crypt/Rijndael.php
Merlin.PHP/library/phpseclib/Crypt/RSA.php
Merlin.PHP/library/phpseclib/Crypt/TripleDES.php
Merlin.PHP/library/phpseclib/Crypt/Twofish.php
Merlin.PHP/images/.DS_Store
Merlin.PHP/images/android-chrome-144x144.png
Merlin.PHP/images/android-chrome-192x192.png
Merlin.PHP/images/android-chrome-36x36.png
Merlin.PHP/images/android-chrome-48x48.png
Merlin.PHP/images/android-chrome-72x72.png
Merlin.PHP/images/android-chrome-96x96.png
Merlin.PHP/images/apple-touch-icon-114x114.png
Merlin.PHP/images/apple-touch-icon-120x120.png
Merlin.PHP/images/apple-touch-icon-144x144.png
Merlin.PHP/images/apple-touch-icon-152x152.png
Merlin.PHP/images/apple-touch-icon-180x180.png
Merlin.PHP/images/apple-touch-icon-57x57.png
Merlin.PHP/images/apple-touch-icon-60x60.png
Merlin.PHP/images/apple-touch-icon-72x72.png
Merlin.PHP/images/apple-touch-icon-76x76.png
Merlin.PHP/images/apple-touch-icon-precomposed.png
Merlin.PHP/images/apple-touch-icon.png
Merlin.PHP/images/browserconfig.xml
Merlin.PHP/images/cursor.png
Merlin.PHP/images/cursor@2x.png
Merlin.PHP/images/favicon-16x16.png
Merlin.PHP/images/favicon-32x32.png
Merlin.PHP/images/favicon-96x96.png
Merlin.PHP/images/Icon.png
Merlin.PHP/images/MacOS_screen.png
Merlin.PHP/images/manifest.json
Merlin.PHP/images/mstile-144x144.png
Merlin.PHP/images/mstile-150x150.png
Merlin.PHP/images/mstile-310x150.png
Merlin.PHP/images/mstile-310x310.png
Merlin.PHP/images/mstile-70x70.png
Merlin.PHP/images/PV.png
Merlin.PHP/images/safari-pinned-tab.svg
Merlin.PHP/images/step1.png
Merlin.PHP/images/step2.png
Merlin.PHP/fonts/.DS_Store
Merlin.PHP/fonts/300.woff
Merlin.PHP/fonts/400.woff
Merlin.PHP/fonts/400i.woff
Merlin.PHP/fonts/600i.woff
Merlin.PHP/fonts/700.woff
Merlin.PHP/fonts/700i.woff
Merlin.PHP/fonts/fontawesome-webfont.eot
Merlin.PHP/fonts/fontawesome-webfont.svg
Merlin.PHP/fonts/fontawesome-webfont.ttf
Merlin.PHP/fonts/fontawesome-webfont.woff
Merlin.PHP/fonts/fontawesome-webfont.woff2
Merlin.PHP/fonts/FontAwesome.otf
Merlin.PHP/fonts/glyphicons-halflings-regular.eot
Merlin.PHP/fonts/glyphicons-halflings-regular.svg
Merlin.PHP/fonts/glyphicons-halflings-regular.ttf
Merlin.PHP/fonts/glyphicons-halflings-regular.woff
Merlin.PHP/fonts/glyphicons-halflings-regular.woff2
Merlin.PHP/config/.DS_Store
Merlin.PHP/config/setting.template.json
Merlin.PHP/config/vpsconfig.template.json
Merlin.PHP/bin/.DS_Store
Merlin.PHP/bin/autoupdate/
Merlin.PHP/bin/install/
Merlin.PHP/bin/nvram/
Merlin.PHP/bin/script/
Merlin.PHP/bin/script/.DS_Store
Merlin.PHP/bin/script/clients.sh
Merlin.PHP/bin/script/dashboard.sh
Merlin.PHP/bin/script/ifconfig-speed.sh
Merlin.PHP/bin/script/netdev-speed.sh
Merlin.PHP/bin/script/netspeed.sh
Merlin.PHP/bin/script/onetime.sh
Merlin.PHP/bin/script/setdns.sh
Merlin.PHP/bin/script/ssback.sh
Merlin.PHP/bin/script/ssconfig.sh
Merlin.PHP/bin/nvram/.DS_Store
Merlin.PHP/bin/nvram/AutoDNS.sh
Merlin.PHP/bin/nvram/autotry.sh
Merlin.PHP/bin/nvram/MDNS.sh
Merlin.PHP/bin/nvram/SaveNVRAM.sh
Merlin.PHP/bin/install/.DS_Store
Merlin.PHP/bin/install/install.sh
Merlin.PHP/bin/autoupdate/.DS_Store
Merlin.PHP/bin/autoupdate/build.sh
Merlin.PHP/bin/autoupdate/check.sh
Merlin.PHP/bin/autoupdate/md5
Merlin.PHP/bin/autoupdate/reinstall.sh
Merlin.PHP/bin/autoupdate/update.sh
Merlin.PHP/assets/.DS_Store
Merlin.PHP/assets/animate.min.css
Merlin.PHP/assets/app.js
Merlin.PHP/assets/bootstrap-theme.css
Merlin.PHP/assets/bootstrap-theme.css.map
Merlin.PHP/assets/bootstrap-theme.min.css
Merlin.PHP/assets/bootstrap-theme.min.css.map
Merlin.PHP/assets/bootstrap.css
Merlin.PHP/assets/bootstrap.css.map
Merlin.PHP/assets/bootstrap.js
Merlin.PHP/assets/bootstrap.min.css
Merlin.PHP/assets/bootstrap.min.css.map
Merlin.PHP/assets/bootstrap.min.js
Merlin.PHP/assets/Chart.bundle.min.js
Merlin.PHP/assets/Chart.min.js
Merlin.PHP/assets/dynamics.min.js
Merlin.PHP/assets/font-awesome.css
Merlin.PHP/assets/font-awesome.min.css
Merlin.PHP/assets/jquery.min.js
Merlin.PHP/assets/list.min.js
Merlin.PHP/assets/logs.js
Merlin.PHP/assets/markdown.min.js
Merlin.PHP/assets/npm.js
Merlin.PHP/assets/standalone.js
Merlin.PHP/assets/style.css
Merlin.PHP/assets/ui.js
Merlin.PHP/assets/underscore-min.js
Merlin.PHP/assets/underscore-min.map
Merlin.PHP/article/.DS_Store
Merlin.PHP/article/error.md
Merlin.PHP/article/help.md
Merlin.PHP/article/update.md

■ copying...
mkdir: can't create directory '/opt/': No such file or directory
cp: can't create '/opt/share/www/README.md': No such file or directory
cp: can't create '/opt/share/www/api.php': No such file or directory
cp: can't create '/opt/share/www/app.php': No such file or directory
cp: can't create directory '/opt/share/www/article': No such file or directory
cp: can't create directory '/opt/share/www/assets': No such file or directory
cp: can't create directory '/opt/share/www/bin': No such file or directory
cp: can't create directory '/opt/share/www/config': No such file or directory
cp: can't create '/opt/share/www/exec.php': No such file or directory
cp: can't create '/opt/share/www/favicon.ico': No such file or directory
cp: can't create directory '/opt/share/www/fonts': No such file or directory
cp: can't create directory '/opt/share/www/images': No such file or directory
cp: can't create '/opt/share/www/index.php': No such file or directory
cp: can't create directory '/opt/share/www/library': No such file or directory
cp: can't create directory '/opt/share/www/pages': No such file or directory
cp: can't create '/opt/share/www/update.php': No such file or directory
■ cd /opt/share/www/
./install.sh: cd: line 60: can't cd to /opt/share/www/
drwxr-xr-x   10 501      20             340 Oct  7 01:51 .
drwxrwxrwx    3 jackiejt root            80 Oct  7 01:51 ..
-rw-r--r--    1 501      20            2636 Sep  5 23:10 README.md
-rw-r--r--    1 501      20             776 Apr  8 11:50 api.php
-rw-r--r--    1 501      20             532 Jul 29  2016 app.php
drwxr-xr-x    2 501      20             120 Oct  7 01:52 article
drwxr-xr-x    2 501      20             600 Oct  7 01:52 assets
drwxr-xr-x    6 501      20             140 Oct  7 01:52 bin
drwxr-xr-x    2 501      20             100 Oct  7 01:52 config
-rw-r--r--    1 501      20             654 Jun 20  2016 exec.php
-rw-r--r--    1 501      20            1350 Jun 20  2016 favicon.ico
drwxr-xr-x    2 501      20             400 Oct  7 01:52 fonts
drwxr-xr-x    2 501      20             760 Oct  7 01:51 images
-rw-r--r--    1 501      20            1001 Sep  6 10:55 index.php
drwxr-xr-x    4 501      20             160 Oct  7 01:51 library
drwxr-xr-x    2 501      20             360 Oct  7 01:51 pages
-rw-r--r--    1 501      20            5136 Aug 26  2016 update.php

■ install done

■ open http://192.168.1.1:81 and enjoy.
■ PS 打開后，進入設定 》使用修正輔助腳本的運行權限功能。

**Comment by qoli** [comment]
■ 「STEP 1」optware 安裝失敗了。
你是不是沒有 U 盤或移動硬盤？
建議 ext2|ext3|ext4 分區格式。

由於一件安裝腳本不容易編寫判斷成功或失敗的命令，所以需要用戶自行注意日誌描述。

**Comment by jackiejtr** [comment]
有啊 是ntfs的 我格式化下

**Comment by ooghost** [comment]
7.6-7.7都没有下载大师了啊，这个已经没法用了，不知道作者升级了7.6-7.7固件没有？

**Comment by qoli** [comment]
wget --no-check-certificate https://github.com/qoli/Merlin.PHP/raw/master/bin/install/install.sh -O install.sh
chmod +x install.sh
./install.sh

新的安裝命令已經不需要下載大師。

**Comment by ooghost** [comment]
好的，收到，谢谢小姐姐～(￣▽￣～)~
