### ISSUE TITLE
#11的问题又重现了，这次u盘格式是ext4没问题

### ISSUE THREAD

**Issue by kingofotaku** [qoli/Merlin.PHP#24]
rt，ext3和4我都试过了，结果都是安装完使用很正常，一旦重启就打不开了。用的是新脚本，虚拟内存选择了512m。报错还是老样子“192.168.1.1:81拒绝了我们的连接请求”

**Comment by qoli** [comment]
**參考這個文章再次格式化 U 盤：**
https://github.com/xzhih/ONMP/blob/master/format-partition.md

確定是首頁的最新下載腳本？

```
curl -LO https://github.com/qoli/Merlin.PHP/raw/master/bin/install/install.sh && chmod +x install.sh && ./install.sh
```

估計你的 U 盤沒格式化好。

**Comment by kingofotaku** [comment]
我按你给的链接里的方法试了一遍，还是不行

**Comment by qoli** [comment]
那么你的固件是最新版吗？
我上网搜索说 380.67 有这个 Bug

**Comment by kingofotaku** [comment]
是的 就是7.8 如果是bug的话软件这边有没有可能做针对性对策

**Comment by qoli** [comment]
试试按照这里的事情
https://www.snbforums.com/threads/entware-after-reboot.10933/

**Comment by kingofotaku** [comment]
不好意思 没找到方法在哪里（英文不行）

**Comment by kingofotaku** [comment]
才发现我是69，不是67（不过也有可能bug没有修复）
