### ISSUE TITLE
报告BUG，管理、切换、测试google3个BUG

### ISSUE THREAD

**Issue by dsyo2008** [qoli/Merlin.PHP#5]
[Imgur](http://i.imgur.com/kvgrUOH.png)
[Imgur](http://i.imgur.com/PY2g4Rz.png)
[Imgur](http://i.imgur.com/cMs8QIi.png)
切换时有2个一起开，其实是一个，应该是BUG
下面测试google，gfw模式一直红色，其他模式绿色，这算是BUG么
还有管理还是192.168.1.1，请修复下

**Comment by qoli** [comment]
1 Google 紅燈：GFW 模式是後來新加的。可用性未知。有很多還沒測試好。
2 管理是被寫定了為 192.168.1.1，還沒做自動獲取 Lan IP。
3 兩個一起開的話，就刷新，或者點一下線路列表那個字，看看反饋結果，Working 應該只有一個 1 的是正常的。再用一下 設定 》重新載入 SS 配置再試一下。

這些問題我找個時間修復一下吧。

**Comment by qoli** [comment]
管理菜單已經調整，用自動更新就可以了。
其他我看看怎麼辦。

**Comment by dsyo2008** [comment]
OK，已更新可以正常。剩下看你修复

**Comment by qoli** [comment]
1. Google 的紅燈我找到了，在非「DNS2SOCKS」就算翻牆正常，也是紅燈的，因為我要 Sock5 23456 的端口。
2. 多個你用設定中的重新載入 ShadowSocks 配置檔試試。
