### ISSUE TITLE
ac88U安装不成功

### ISSUE THREAD

**Issue by supra007** [qoli/Merlin.PHP#8]
安装完成了，但无法连接。安装过程中中间出现过lightpad is not found，ipkg: not found。我现在的固件是梅林6.61，是不是不支持AC88U啊。问下JFFS要打开吗？

**Comment by qoli** [comment]
![image](https://github.com/qoli/Merlin.PHP/raw/master/images/step2.png)

請使用 USB 接口連上外部儲存設備后運行這一步。
[百度搜索](https://www.baidu.com/s?wd=merlin+download+master&rsv_spt=1&rsv_iqid=0xf0971696000a577e&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=&tn=baiduhome_pg&rsv_enter=1&inputT=7415)
