### ISSUE TITLE
網路類型: null

### ISSUE THREAD

**Issue by Sumnus520** [qoli/Merlin.PHP#9]
1.网络类型一直显示为NULL

Jul 30 10:06:44 lwsts[808]: websocket writing but the buf_info is null
Jul 30 10:06:45 login[10518]: root login on 'pts/1'
Jul 30 10:06:46 lwsts[10540]: ERROR on binding to port 16661 (-1 98)
Jul 30 10:06:46 lwsts[10540]: libwebsocket init failed
Jul 30 10:06:48 lwsts[808]: websocket writing but the buf_info is null
这个是后台的错误日志不知道有没有关联，还有我的路由器管理用户名不是root
2.SS线路列表里面没有显示目前在使用什么线路
就是那个绿色开关不能实时显示哪条线路是开着的
http://v1.freep.cn/3tb_160730102007tu8a512293.jpg
-

**Comment by qoli** [comment]
進入設定 》重新載入 SS 配置。

網絡類型那裡我再看看。

**Comment by qoli** [comment]
網絡類型已經修正了。還是 null 請重新報告吧。
